### PR TITLE
Update functions used to write to EEPROM

### PR DESCRIPTION
**Pull request by eltang**

### CODE REVIEW

**Comment by abcminiuser** [comment]
Great idea! And yes, I should know better than to use the write functions over the update functions. I'll merge this in tonight.

**Comment by eltang** [comment]
Awesome. Since you are familiar with the new functions (you even made a tutorial that recommended their use), I wasn't too sure why the old functions were still there. I don't know how the trailing newlines got removed. My text editor must be acting up.

**Comment by NicoHood** [comment]
The update functions take more flash. That might be a point for a bootloader. However it should not be too much, so I suggest to merge it.

**Comment by eltang** [comment]
@NicoHood If I'm not mistaken, flash memory for the boot loader is allocated in large chunks (512 bytes?), meaning that a small increase in code size does not make a difference unless it pushes the size of the code over the next size threshold.

**Comment by NicoHood** [comment]
zeah and this 4kb threshold is critical. I have coded some bootloader and I know that 4kb will fill up verz fast. And because of this reason eeprom is mostlz not used anzwazs because it simply does not fit into 4kb.

**Comment by abcminiuser** [comment]
I do vaguely remember it being a size issue - but I don't think the current code and current GCC compiles *that* close to the 4KB boundary that it will be an issue. I'll merge this now, and I can revert it later on if it turns out to be a problem.

**Comment by NicoHood** [comment]
You can change the switch case of the descriptors.c into an if/else which will reduce the size. ;)

**Comment by eltang** [comment]
Apparently the trailing newlines weren't removed, so it must be GitHub that's acting up.

**Pull request merged**
