### PR TITLE
Update BootloaderCDC.c

### LINKED ISSUE #44: Critical CDC Bootloader USB HUB bug
This issue has **nothing** to do with issue #42.

The story:
I am developing a 16u2 CDC Bootloader variation and I got a very weird error. I tried with my arduino leonardo now. There is no such an error (with the official bootloader). Then I recompiled the CDC Bootloader from lufa and the bug appeared.

The bug:
Use a USB3 port on your pc (tried with two pcs) and connect a usb 2.0 hub to it(usb 3 wont cause the bug). plug in the arduino with the cdc bootloader and try to upload a sketch via the ide. The verification will fail. Now do the same and connect a second device to the usb port like a mouse. For some reason the uploading now doesnt fail.

The sketch will upload anyways but the verification wont fail. I tried with 2 different pcs and different os. (win7, win8, ubuntu). I tried 4 different usb 2 hubs (usb 3 works). I did not try usb 2 pc host ports because i only have usb3 ports. I tried different drivers for windows (shouldnt matter cause linux has this bug too).

There are also different errors like a "dead" usb port until you plug in/out another device on the hub. As long as you dont do this, the cdc bootloader usb port will be dead, you can replug it as long as you want.

It seems that the old CDC bootloader from the Arduino team (with older lufa) has not this problem. I am now searching for the error. If it is the lufa version or the code of the bootloader.

Fuses used (tested with 16u2, 32u2 and 32u4):
```
#fuses (HoodLoader2 only, not suitable for DFU)
HoodLoader2atmega16u2.bootloader.low_fuses=0xFF
HoodLoader2atmega16u2.bootloader.high_fuses=0xD8
HoodLoader2atmega16u2.bootloader.extended_fuses=0xCB (0xFC for 32u4)
HoodLoader2atmega16u2.bootloader.unlock_bits=0x3F
HoodLoader2atmega16u2.bootloader.lock_bits=0x2F
```

To recreate this you only need an Arduino Uno/Mega (16u2) board or a leonardo/(pro)micro(32u4) board and test one of the versions. To upload sketches to the 16u2 you need my hid project and hoodloader2 project on github. It'd be easier to test the 32u4 though.

edit: @Dean: any idea where the bug could be located, where i have to start searching?

### PR DESCRIPTION
**Pull request by NicoHood**
Fixes #44

### CODE REVIEW

**Comment by abcminiuser** [comment]
Thanks NicoHood!

**Comment by NicoHood** [comment]
Did you test this? I think it is just waiting a bit before releasing the line (technical thing) and nothing else.

**Comment by abcminiuser** [comment]
No - I actually don't have any USB3 hosts at the moment (I'm looking for a replacement laptop, but haven't found one to my liking yet). That said, the patch shouldn't break existing functionality so I'm fine with it if it fixes your edge-case.

**Comment by NicoHood** [comment]
And I had no chance to test USB2 Host. Have you tested that? Maybe its the same problem there.

**Pull request merged**
