### PR TITLE
CCID: Support for Get and Set Parameters

### PR DESCRIPTION
**Pull request by kidbomb**
This push request add support for 2 USB CCID messages:
 * GetParameters
 * SetParameters

### CODE REVIEW

**Comment by kidbomb** [comment]
The CCID layer is already mature at this point, so as far as applications are concerned, I believe we could merge it to the main branch now. However, I still intend to add some basic support for ISO7816 into the demos, and that could take a while. I plan to do this incrementally, and I already have some basic functionality at place, which I will create a pull request for as soon as this first PR got approval.

**Comment by abcminiuser** [comment]
Ok, did a little cleanup. Last round I think - double check the branch state and I'll create the final merge request.

**Comment by kidbomb** [comment]
The branch looks good - I'll double check today by running the tests and as soon as it is done I'll let you know.

**Comment by kidbomb** [comment]
Tests looks good - let's merge it to master then!

**Pull request merged**
